language: objective-c
osx_image: xcode11
# xcode_sdk: iphonesimulator11
# xcode_project: Loop.xcodeproj
# xcode_scheme: Loop

addons:
  homebrew:
    packages:
    - carthage
    update: true
before_script:
    - git config --global protocol.version 1
    - gem install xcpretty xcpretty-travis-formatter --quiet
    - set -o pipefail && xcodebuild -project Loop.xcodeproj -target Cartfile  | tee cartfile-xcodebuild.log | xcpretty -f `xcpretty-travis-formatter` --report html
script:
    # Build the app target
    - set -o pipefail && xcodebuild -project Loop.xcodeproj -scheme Loop build CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO  | tee loop-build-xcodebuild.log | xcpretty -f `xcpretty-travis-formatter` --report html
    - set -o pipefail && xcodebuild -project Loop.xcodeproj -scheme Learn build CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO  | tee learn-build-xcodebuild.log | xcpretty -f `xcpretty-travis-formatter` --report html
    # Run the test target
    - set -o pipefail && xcodebuild -project Loop.xcodeproj -scheme LoopTests -destination 'name=iPhone 8' test  | tee loop-test-xcodebuild.log | xcpretty -f `xcpretty-travis-formatter` --report html
    - set -o pipefail && xcodebuild -project Loop.xcodeproj -scheme DoseMathTests -destination 'name=iPhone 8' test  | tee dose-math-test-xcodebuild.log | xcpretty -f `xcpretty-travis-formatter` --report html 
