language: objective-c
osx_image: xcode12
# xcode_sdk: iphonesimulator11
# xcode_project: Loop.xcodeproj
# xcode_scheme: Loop

addons:
  homebrew:
    packages:
    - carthage
    update: true
jobs:
  include:
    - stage: build
      before_install: git config --global protocol.version 1
      install: gem install xcpretty xcpretty-travis-formatter --quiet
      before_script: make travis-before
      script:
          - make travis-build
    - stage: test
      before_install: git config --global protocol.version 1
      install: gem install xcpretty xcpretty-travis-formatter --quiet
      before_script: make travis-before
      script:
          - make travis-test