language: objective-c
osx_image: xcode12
# xcode_sdk: iphonesimulator11
# xcode_project: Loop.xcodeproj
# xcode_scheme: Loop

addons:
  homebrew:
    packages:
    - carthage
    update: true
install:
    - git config --global protocol.version 1
    - gem install xcpretty xcpretty-travis-formatter --quiet
    - make travis-before
jobs:
  include:
    - stage: build
      script:
          - make travis-build
    - stage: test
      script:
          - make travis-test